### ISSUE TITLE
WSM - OIDC configuration not passed to the container

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#262]
**Description**

OIDC configuration is not passed along to the deployment in full:

`values.yaml`

```
 global:
[...]
  auth:
    sessionLengthHours: 720
    oidc:
      clientId: "xxxxxxxxxxxxxxx"
      secret: "SuperS3cret"
      authMethod: "pkce"
      issuer: "https://this-is-a-test.okta.com"
[...]
```

Apply the new configuration

```
$ wsm deploy --spec values-wsm.yaml

  Deploying wandb completed.
```

Result in the pod

```
kubectl exec -ti wandb-app-9cc668b8c-n2xq6 -c app -- env | grep -iE 'OIDC|SECRET|AUTH'
OIDC_AUTH_METHOD=
OIDC_ISSUER=https://this-is-a-test.okta.com
OIDC_CLIENT_ID=xxxxxxxxxxxxxxx
```
The OIDC method was not set, and neither was the OIDC_CLIENT_SECRET set.

**Comment by zacharyblasczyk** [comment]
@vijay-wandb, `values.yaml`  != `values-wsm.yaml` was that just a typo in the issue?

**Comment by flamarion** [comment]
There was no mistake with the values. I probably typed the `values.yaml` but the actual file name was the other one, which I probably copied.
In any case, I tested the SSO configuration right now with the WSM and it's picking the configuration without any problems.

```
kubectl exec -ti **wandb-app-57f9cc95b4-gvzlk** -c app -- env | grep -iE 'OIDC|SECRET|AUTH'
OIDC_ISSUER=dev-53803758.okta.com
GORILLA_CUSTOMER_SECRET_STORE_K8S_CONFIG_NAMESPACE=default
OIDC_CLIENT_ID=0oajickg1yfUx8Cp85d7
OIDC_AUTH_METHOD=pkce
OIDC_CLIENT_SECRET=
``` 
Values from the spec file

```
wandb:
  global:
[...]
    auth:
      oidc:
        clientId: "0oajickg1yfUx8Cp85d7"
        authMethod: "pkce"
        issuer: "dev-53803758.okta.com"
[...]
```

However, after removing the OIDC configuration and a new pod is created, the env vars continue set and the SSO continue enabled 

```
wandb@**wandb-app-cf7bdf7db-wrz26**:~$ env | grep -iE 'OIDC|SECRET|AUTH'
GORILLA_AUTH_METHOD=pkce
GORILLA_OIDC_CLIENT_ID=0oajickg1yfUx8Cp85d7
MINIO_SECRET_KEY=wandb_local
GORILLA_CUSTOMER_SECRET_STORE_SOURCE=noop://
GORILLA_OIDC_ISSUER=dev-53803758.okta.com
```

Values from spec file

```
wandb:
  global:
    host: http://wandb.home.lab
[...]
    # auth:
    #   oidc:
    #     clientId: "0oajickg1yfUx8Cp85d7"
    #     authMethod: "pkce"
    #     issuer: "dev-53803758.okta.com"
[...]
```

Once removed from spec, it's also not visible in the console, so I suspect it's coming from the `wandb-env.tar.gz` stored in the Object Storage.

Copy and extract the `wandb-env.tar.gz` from bucket

```
 $ mc cp cephlab/wandb/wandb-env.tar.gz ~/Downloads/
...pves3.home.lab/wandb/wandb-env.tar.gz: 3.93 KiB / 3.93 KiB 

$ tar -zxvf ~/Downloads/wandb-env.tar.gz
x jwks.json
x key.pem
x kid.txt
x session.txt
x settings.json
x users.htpasswd
```

Inspect the `settings.json`
```
 $ jq -r < settings.json
{
 [...]
  "ssoEnable": true,
  "oidcClientID": "0oajickg1yfUx8Cp85d7",
  "oidcSecret": "",
  "oidcIssuer": "dev-53803758.okta.com",
  "authMethod": "pkce",
 [...]
```
After removing the `wandb-env.tar.gz` from the object storage and restarting the application, then the SSO is disabled as expected.
```
$ mc rm cephlab/wandb/wandb-env.tar.gz
Removed `cephlab/wandb/wandb-env.tar.gz`.
$ kubectl rollout restart deployment wandb-app
deployment.apps/wandb-app restarted
````

Checking the new pod, the env vars are not set anymore 
```
wandb@**wandb-app-5b4bc69847-fvsw**9:~$ env | grep -iE 'OIDC|SECRET|AUTH'
GORILLA_AUTH_METHOD=
GORILLA_OIDC_CLIENT_ID=
MINIO_SECRET_KEY=wandb_local
GORILLA_CUSTOMER_SECRET_STORE_SOURCE=noop://
GORILLA_OIDC_ISSUER=
```

This reinforce the theory that values from `wandb-env.tar.gz` are taking precedence of values set by Operator
