### ISSUE TITLE
Operator Feature Request | Tag Image Digest

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#275]
Despite using just the image digest (@sha256:...), the operator appears to append a tag automatically. This is breaking deployments since Kubernetes does not support both a tag and a digest together.

**Steps to Reproduce:**

1. Create or modify a CR to reference an image by its digest without specifying a tag:

```
app:
  image:
    repository: default-route-openshift-image-registry.apps-crc.testing/test2/wandb-local@sha256:95f854ed3dbe56290c6bad543aa55ce77986d5c444be2d71388c76ea0aea091b
    # No tag specified
```

2. Apply the CR:
`oc apply -f cr.yaml`

3. The operator processes the resource, but the deployment fails with the following error:
`Warning  InspectFailed  kubelet  Failed to apply default image tag "<image-ref>:": couldn't parse image name "<image-ref>:": invalid reference format`

Expected Behavior:
The operator should respect the image digest and not append any tag (especially an empty tag :) when using a digest reference in the CR.

**Comment by jsbroks** [comment]
```yaml
app:
  image:
    repository: default-route-openshift-image-registry.apps-crc.testing/test2/wandb-local@sha25
    tag: 95f854ed3dbe56290c6bad543aa55ce77986d5c444be2d71388c76ea0aea091b
```
