### ISSUE TITLE
Feature Request Operator | Support to pull Bucket credentials from secrets in the CR

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#283]
Description

Add support to pull Bucket credentials from Secrets when deploying CRD from yaml file. 
[helm-charts/charts/operator-wandb/values.yaml at main · wandb/helm-charts](https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/values.yaml#L89-L101)

 ```
# Storage bucket that will be used by the application by default but can be overridden by the user in the wandb-console.
  defaultBucket:
    # az, s3, gcs
    provider: "s3"
    name: ""
    path: ""
    region: ""
    kmsKey: ""
    secretKey: ""
    accessKey: ""
```

  # If specified the application will use this bucket for all storage operations, and will not be overridable by the user.
  bucket: {}
