### ISSUE TITLE
Feature Request Operator | Support to pull MySQL credentials from secrets in the CR

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#284]
Description

Add support to pull MySQL credentials from Secrets when deploying CRD from yaml file. 

[helm-charts/charts/operator-wandb/values.yaml at main · wandb/helm-charts](https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/values.yaml#L55-L60) 

  ```
mysql:
    host: ""
    port: 3306
    database: "wandb_local"
    user: "wandb"
    password: ""
```

This can be the entire configuration like we do [here](https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/charts/mysql/templates/statefulset.yaml#L39-L57) or at least the password pulled from secrets. Ex. what can look like the password

  ```
env:
    - name: MYSQL_PASS
      valueFrom:
        secretKeyRef:
          name: mysql-data
          key: mysql-pass
  mysql:
    host: ""
    port: 3306
    database: "wandb_local"
    user: "wandb"
    password: $(MYSQL_PASS)
```
