### ISSUE TITLE
Feature Request | Support ClickHouse and Kafka passwords as secret key variables

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#307]
Support ClickHouse and Kafka passwords as secret key variables

Current structure uses hardcoded passwords

 
``` clickhouse:
    install: false
    host: ""
    port: 8443
    password: "fake"
    database: "weave_trace_db"
    user: "default"
```
```
  kafka:
    # The following values are anchored here, and referenced by alias later for
    # the kafka dependency chart.
    user: &kafkaUser "wandb"
    password: &kafkaPassword "wandb"
    brokerHost: ""
    brokerPort: 9092
    runUpdatesShadowTopic: ""
    # This value will only apply upon initial topic creation.
    # If the topic already exists then changing the number of partitions is not possible.
    runUpdatesShadowNumPartitions: 12
```
```
# It is *strongly* recommended to supply passwords yourself for production installs.
kafka:
  install: false
  controller:
    persistence:
      size: 30Gi
  sasl:
    interbroker:
      password: "inter-broker"
    controller:
      password: "controller-pw"
    # The client usernames and passwords are alias references from the global values section at the beginning of this file.
    # Please update the values there to ensure proper propagation to the application
    client:
      users:
        - *kafkaUser
      passwords: *kafkaPassword
```
